
DROP TABLE SOSO_USER;

SELECT * FROM SOSO_USER;

CREATE TABLE SOSO_USER(
      USER_NO NUMBER PRIMARY KEY,
      USER_PR VARCHAR2(30) NOT NULL,
      USER_NAME VARCHAR2(30)NOT NULL,
      USER_ID VARCHAR(20) UNIQUE NOT NULL,
      USER_PW VARCHAR(100) NOT NULL,
      USER_NN VARCHAR(50) UNIQUE NOT NULL,
      GRADE NUMBER NOT NULL,
      ADDR VARCHAR2(4000) NOT NULL,
      PHONE NUMBER NOT NULL,
      EMAIL VARCHAR2(1000) NOT NULL,
      CONSTRAINT soso_user_grade CHECK (GRADE IN(1,2,3))
);

CREATE SEQUENCE USER_NO_SQ NOCACHE;

INSERT INTO SOSO_USER VALUES(
    USER_NO_SQ.NEXTVAL,'김미영','최재윤','my1007','test1234','테스트용닉네임',2,
    '서울시 강남구 개포동 어쩌구저쩌구 123-1101',01098765432,'test123@gmail.com',
    DEFAULT,DEFAULT,DEFAULT,DEFAULT
);


SELECT * FROM SOSO_USER;

CREATE TABLE SOSO_USER(
      USER_NO NUMBER PRIMARY KEY,
      USER_PR VARCHAR2(30) NOT NULL,
      USER_NAME VARCHAR2(30)NOT NULL,
      USER_ID VARCHAR(20) UNIQUE NOT NULL,
      USER_PW VARCHAR(100) NOT NULL,
      USER_NN VARCHAR(50) UNIQUE NOT NULL,
      GRADE NUMBER NOT NULL,
      ADDR VARCHAR2(4000) NOT NULL,
      PHONE NUMBER NOT NULL,
      EMAIL VARCHAR2(1000) NOT NULL,
      USER_POINT NUMBER DEFAULT 100 NOT NULL ,
      SUB_YN CHAR(1) DEFAULT 'N' NOT NULL ,
      ENABLED_YN CHAR(1) DEFAULT 'N' NOT NULL,
      USER_TYPE VARCHAR2(5) DEFAULT 'USER' NOT NULL,
      CONSTRAINT soso_user_grade CHECK (GRADE IN(1,2,3)),
      CONSTRAINT soso_user_sub CHECK (SUB_YN IN ('Y','N')),
      CONSTRAINT soso_user_enabled CHECK (ENABLED_YN IN ('Y','N')), 
      CONSTRAINT soso_user_user_type CHECK (USER_TYPE IN ('USER','ADMIN'))
);

INSERT INTO SOSO_USER VALUES(
    USER_NO_SQ.NEXTVAL,'김미영','최재윤','my1007','test1234','테스트용닉네임',2,
    '서울시 강남구 개포동 어쩌구저쩌구 123-1101',01098765432,'test123@gmail.com',
    DEFAULT,DEFAULT,DEFAULT,DEFAULT
);